### ISSUE TITLE
CheckInterval is the same as TTL

### ISSUE THREAD

**Issue by cobyge** [mholt/caddy-dynamicdns#25]
In the README, it is implied that `check_interval` is used for setting how often to check the external IP.  
There is an unexpected side effect though, as the same value is used as the TTL of the record.  
I believe this is unexpected (and unwanted) behavior, and also prevents putting low intervals (Anything lower than 5 minutes is rejected by Cloudflare).

I think there should be a different value for setting the TTL, as opposed to the checking interval.

**Comment by mholt** [comment]
I guess we could separate them. I haven't heard of a use case for checks more frequent than 5m before. Why do you need to check that often?

Because it makes sense for CheckInterval to roughly be the TTL, since we're not doing lookups more often than CheckInterval. :man_shrugging: 

But if there's a good use case for this I guess we can separate them out.

**Comment by mholt** [comment]
I'll implement a new TTL config parameter. What should the default be? (Empty/Zero?)

**Comment by cobyge** [comment]
From the (admittedly little) time I just spent playing around with libdns, it looks like leaving the field empty doesn't cause any problems (I only tested this on [libdns/cloudflare](https://github.com/libdns/cloudflare).  
Another option is to have the default be equal to the CheckInterval.

**Comment by mholt** [comment]
Should be configurable now -- at least, in the JSON config!
